# Generated by Django 2.2.1 on 2019-06-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Album',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('born', models.DateTimeField(verbose_name='Date de naissance')),
                ('bio', models.TextField()),
                ('discographie', models.ForeignKey(null=True, on_delete='', to='musique.Album')),
            ],
            options={
                'verbose_name': 'Artiste',
                'ordering': ['name'],
            },
        ),
    ]
