# Generated by Django 2.2.1 on 2019-06-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiste',
            name='discographie',
        ),
        migrations.RemoveField(
            model_name='artiste',
            name='firstName',
        ),
    ]
