# Generated by Django 2.2.1 on 2019-06-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0002_auto_20190607_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiste',
            name='born',
        ),
    ]
