# Generated by Django 2.2.1 on 2019-06-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0003_remove_artiste_born'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='bio',
        ),
        migrations.AddField(
            model_name='album',
            name='infos',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='musiques',
            field=models.TextField(null=True),
        ),
    ]
