# Generated by Django 2.2.1 on 2019-06-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0005_artiste_discographie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='discographie',
            field=models.ManyToManyField(null=True, related_name='artistes', to='musique.Album'),
        ),
    ]
