# Generated by Django 2.2.1 on 2019-06-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0006_auto_20190607_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artistes',
            field=models.ManyToManyField(related_name='artistes', to='musique.Artiste'),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='discographie',
            field=models.ManyToManyField(blank=True, to='musique.Album'),
        ),
    ]
