# Generated by Django 2.2.1 on 2019-06-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0008_auto_20190607_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artiste',
            old_name='discographie',
            new_name='albums',
        ),
    ]
