# Generated by Django 2.2.1 on 2019-06-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0009_auto_20190607_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artistes',
        ),
        migrations.RemoveField(
            model_name='artiste',
            name='albums',
        ),
    ]
