# Generated by Django 2.2.1 on 2019-06-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0010_auto_20190607_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artistes',
            field=models.ManyToManyField(related_name='artistes', to='musique.Artiste'),
        ),
        migrations.AddField(
            model_name='artiste',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='albums', to='musique.Album'),
        ),
    ]
