# Generated by Django 2.2.1 on 2019-06-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0011_auto_20190607_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='sortie',
            field=models.DateField(null=True),
        ),
    ]
