# Generated by Django 2.2.1 on 2019-06-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0012_album_sortie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='sortie',
        ),
    ]
