# Generated by Django 2.2.1 on 2019-06-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0013_remove_album_sortie'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='pochette',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artiste',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
